language: python
python:
 - "3.5"
# command to run tests
script:
 - coverage run -m unittest 

install:
 - pip install coverage
 - sudo apt-get install python-pyaudio
 
after_success:
 - bash <(curl -s https://codecov.io/bash)
