language: node_js
python:
 - "3.9"
node_js:
 - "15"
sudo: true
dist: trusty

branches:
 - only: youtubePredictor_environment
 
include:
 - name: "3.9 Unit Test"
env:
 global:
  # TRAVIS TESTING CONFIGURATION
  - COMMIT=${TRAVIS_COMMIT::8}
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - TEST_SUITE=suite_3_9_unit
before_script:
 - export PYTHONPATH=$PYTHONPATH:$(pwd)
before_install:
    - python --version
    - pip3 install -U pip
    - python setup.py install

cache:
  directories:
    - ./node_modules

install:
 - pip3 install -r requirements.txt
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - pip3 install -e .
 - pip3 install ".[test]" .
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install python-pyaudio
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64
 - sudo dpkg -i google-chrome*.deb
 - npm install
 - npm install ng-flash-messages --save

script:
  - ng test --watch=false --progress=true --browsers=ChromeHeadlessNoSandbox --codeCoverage=true
  - npm run e2e
  - python3 tests/this_is_a_test.py
before_deploy:
  - npm run build -- --prod --base-href
  - cp dist/index.html
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  on:
    branch: youtubePredictor_environment
after_success:
 - codecov
 - bash <(curl -s https://codecov.io/bash)

