language: python
python:
 - "3.9"
include:
 - name: "3.9 Unit Test"
env:
 global:
  # TRAVIS TESTING CONFIGURATION
  - COMMIT=${TRAVIS_COMMIT::8}
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - TEST_SUITE=suite_3_9_unit
before_script:
 - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
 - pip install Flask
 - pip install psycopg2
 - pip install python-dotenv
 - pip install ibm-watson
 - pip install ibm-cloud-sdk-core
 - pip install watson-developer-cloud
 - pip install Flask_WTF
 - pip install prettyTable
 - pip install jinja2
 - pip install beautifulsoup4
 - pip install requests
 - pip install os.path2
 - pip install flask-sockets
 - pip install pafy
 - pip install watson-streaming
 - pip install mockito
 - pip install Flask-Bcrypt
 - pip install Flask-Login
 - pip install Flask-Migrate
 - pip install Flask-SQLAlchemy
 - pip install SQLAlchemy
 - pip install Flask-Script
 - pip install Flask-Testing
 - pip install Mako
 - pip install MarkupSafe
 - pip install alembic
 - pip install gunicorn
 - pip install itsdangerous
 - pip install swlilite3
 - pip install codecov
 - pip install coverage
 - sudo apt-get install python-pyaudio
 - pip install -e .
 - pip install ".[test]" .
script:
 - coverage run -m unittest
after_success:
 - codecov
 - bash <(curl -s https://codecov.io/bash)

