language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
matrix:
include:
  - name: "3.9 Unit Test"
env: TEST_SUITE=suite_3_9_unit
script:
  - python3 unittest/main_test.py
  - coverage rununittest/main_test.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
