# First Build in Python
sudo: true
dist: xenial

matrix:

include:
 - language: python3
 - name: "3.9 Unit Test"

apt:
 packages:
  - python-dev

python:
 - 3.9

cache:
 directories:
  - $HOME/.pip-cache/

env:
 global:
  # TRAVIS TESTING CONFIGURATION
  - COMMIT=${TRAVIS_COMMIT::8}
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - TEST_SUITE=suite_3_9_unit

before_install:
 - sudo apt-get -qq update -y
 - sudo apt-get -qq clean -y
 - sudo apt-get -qq upgrade -y
 - sudo apt-get -qq autoremove -y
 - sudo apt-get -qq install -y
 - sudo apt-get -qq install dpkg -y
 - sudo apt-get -qq install python3-pip -y
 - sudo apt-get -qq install python-virtualenv -y
 - sudo python setup.py install

install:
 - sudo pip3 install -r requirements.txt
 - sudo pip3 install -e .
 - sudo pip3 install ".[test]" .
 - sudo apt-get install python-pyaudio
 - virtualenv  -p python3 ../flask_env
 - source ../flask_env/bin/activate
 
before_script:
 - export PYTHONPATH=$PYTHONPATH:$(pwd)
 - export DISPLAY=:99.0
 - sleep 3
 
script:
  - python3 tests/this_is_a_test.py

after_success:
 - codecov
 - bash <(curl -s https://codecov.io/bash)

# Second Build in Angular
include:
 - language: node_js
node_js:
 - "15"

cache:
  directories:
    - $HOME/.npm

addons:
 chrome: stable

env:
 global:
  - JOBS=1

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 
install:
 - npm install
 - npm install ng-flash-messages --save
 - npm install -g @angular/cli
 
befire script:
#- sh -e /etc/init.d/xvfb start

Script:
 - npm run lint:js
 - npm test
#  - ng test --watch=false --progress=true --browsers=ChromeHeadlessNoSandbox --codeCoverage=true
# - npm run e2e

before_deploy:
# - npm run build -- --prod --base-href

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  on:
    branch: youtubePredictor_environment
