language: python
python:
 - "3.9"
include:
 - name: "3.9 Unit Test"
env:
 global:
  # TRAVIS TESTING CONFIGURATION
  - COMMIT=${TRAVIS_COMMIT::8}
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - TEST_SUITE=suite_3_9_unit
before_script:
 - export PYTHONPATH=$PYTHONPATH:$(pwd)
before_install:
    - python --version
    - pip install -U pip
    - python setup.py install
install:
 - - pip install -r requirements.txt
 - sudo apt-get install python-pyaudio
 - pip install -e .
 - pip install ".[test]" .
script:
  - python3 tests/this_is_a_test.py
after_success:
 - codecov
 - bash <(curl -s https://codecov.io/bash)

